version: "3"

services:
  database:
    image: mysql:5.7
    container_name: cepre-database
    environment:
      MYSQL_DATABASE: 'cepre'
      MYSQL_USER: 'cepre'
      MYSQL_PASSWORD: 'cepre'
      MYSQL_ROOT_PASSWORD: 'cepre'
    networks:
      - int-nw
      - out-nw
    ports:
      - 43286:3306
  app:
    build: ./api
    container_name: cepre-api
    environment:
      HTTP_PROXY: 'http://192.168.1.36:9128'
      HTTPS_PROXY: 'http://192.168.1.36:9128'
    depends_on:
      - database
    networks:
      - int-nw
      - out-nw
    volumes:
      - ./api:/api
    ports:
      - 20901:8080
  web:
    image: nginx:1.15.8
    container_name: cepre-web
    restart: unless-stopped
    volumes:
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - ./web:/usr/share/nginx/html
    ports:
      - 20900:80

        

networks:
  int-nw:
    internal: true
  out-nw:
    internal: false
