# Generated by Django 3.2 on 2022-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_docente',
            name='fecha_sesion',
            field=models.DateTimeField(verbose_name='Fecha registro'),
        ),
    ]
