# Generated by Django 3.2 on 2022-01-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_asistencia_docente_fecha_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_docente',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario'),
        ),
    ]
