# Generated by Django 3.2 on 2022-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220124_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_grupo',
            name='permitir_blancos',
            field=models.BooleanField(default=False, verbose_name='Permitir preguntas en blanco'),
        ),
        migrations.AddField(
            model_name='examen_grupo',
            name='puntaje_blanco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje de preguntas en blanco'),
        ),
        migrations.AddField(
            model_name='examen_grupo',
            name='puntaje_correcto',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Puntaje de preguntas correctas'),
        ),
        migrations.AddField(
            model_name='examen_grupo',
            name='puntaje_errado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje de preguntas en erradas'),
        ),
    ]
