# Generated by Django 3.2 on 2022-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220311_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='examen_rendido',
            field=models.BooleanField(default=False, verbose_name='Examen ya rendido'),
        ),
    ]
