# Generated by Django 3.2 on 2022-03-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_examen_examen_rendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='lanzar_examen',
            field=models.BooleanField(default=False, verbose_name='Lanzar examen'),
        ),
        migrations.AddField(
            model_name='resultados_examen_estudiante',
            name='nota_respuesta',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Nota por pregunta'),
        ),
        migrations.AlterField(
            model_name='resultados_examen_estudiante',
            name='estado_respuesta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estado de respuesta'),
        ),
        migrations.AlterField(
            model_name='resultados_examen_estudiante',
            name='letra_respuesta',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Letra de respuesta'),
        ),
        migrations.CreateModel(
            name='examen_grupo_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('ultima_pregunta', models.IntegerField(default=0, verbose_name='ultimapreg')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estudiante')),
                ('id_examen_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.examen_grupo')),
            ],
            options={
                'verbose_name': 'Examen grupo de estudiantes',
                'verbose_name_plural': 'Examenes grupo de estudiantes',
                'ordering': ['id'],
            },
        ),
    ]
