# Generated by Django 3.2 on 2022-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220314_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_estudiante',
            name='nota_promedio',
            field=models.CharField(default='NSP', max_length=5, verbose_name='Nota Promedio'),
        ),
    ]
