# Generated by Django 3.2 on 2022-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_examen_estudiante_nota_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados_examen_estudiante',
            name='nro_pregunta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nro de pregunta'),
        ),
    ]
