# Generated by Django 3.2 on 2022-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_examen_estudiante_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_estudiante',
            name='esta_finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='examen_estudiante',
            name='esta_iniciado',
            field=models.BooleanField(default=False, verbose_name='Examen iniciado'),
        ),
    ]
