# Generated by Django 3.2 on 2022-04-07 14:08

import app.scrap
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220401_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balota_preguntas_curso',
            name='img_pregunta',
            field=models.ImageField(blank=True, null=True, upload_to=app.scrap.path_preguntas_balota_curso, verbose_name='Imagen'),
        ),
    ]
