# Generated by Django 3.2 on 2022-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_balota_preguntas_curso_img_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_estudiante',
            name='nota_promedio',
            field=models.CharField(default='NSP', max_length=10, verbose_name='Nota Promedio'),
        ),
    ]
