# Generated by Django 3.2 on 2022-09-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_examen_estudiante_nota_promedio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla_configuraciones',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='URL_tesoreria',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='direccion_pago_fisico',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='fuente_datos_persona',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='mostrar_enlace_tesoreria',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='mostrar_pago_fisico',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='mostrar_pago_virtual',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='validacion_email',
        ),
        migrations.RemoveField(
            model_name='tabla_configuraciones',
            name='validacion_telefono',
        ),
        migrations.AddField(
            model_name='tabla_configuraciones',
            name='clave',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabla_configuraciones',
            name='valor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
