# Generated by Django 3.2 on 2022-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220902_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_configuraciones',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
