# Generated by Django 3.2 on 2022-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tabla_configuraciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pago',
            name='concepto',
            field=models.CharField(max_length=200, null=True, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='ide_esp',
            field=models.PositiveIntegerField(null=True, verbose_name='ID ESP'),
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='ide_itm',
            field=models.PositiveIntegerField(null=True, verbose_name='ID ITEM'),
        ),
    ]
