# Generated by Django 3.2 on 2022-10-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220919_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='id_curso',
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_colegio',
            field=models.CharField(choices=[('PR', 'Privado'), ('PU', 'Publico'), ('---', 'NO ESPECIFICA')], max_length=10, verbose_name='Tipo de Colegio'),
        ),
        migrations.CreateModel(
            name='docente_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.padron_curso')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.docente')),
            ],
            options={
                'verbose_name': 'Docente Curso',
                'verbose_name_plural': 'Docente Cursos Dictar',
                'ordering': ['id'],
            },
        ),
    ]
